name: 'Trufflehog Actions Scan'
description: 'Scan repository for secrets with basic trufflehog defaults in place for easy setup.'
author: 'Ed Plato'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  githubToken:
    description: 'GitHub Token to access a privat repository'
    required: false
branding:
  icon: 'shield'  
  color: 'yellow'
